### ISSUE TITLE
KeyError: ' 输入其他的代码会提示是什么原因呢

### ISSUE THREAD

**Issue by luolovehk** [sorahjy/fund-excess-returns-checker#1]
Traceback (most recent call last):
  File "C:\jj\generate_output.py", line 85, in <module>
    worksheet.cell(3 + ind, 2, tmp_data[item][1])  # name
KeyError: '

**Comment by sorahjy** [comment]
你可以检查一下你自己加入的代码的格式是否正确？，或者把fund.py文件贴一段上来我看下

**Comment by luolovehk** [comment]
import json

compare_index = ["485111", "110003"]

fund = [
     "510300",
]

fund_extra = [
    "485111",
]


def get_funds():
    return {'compare_index': compare_index, 'fund': fund, 'fund_extra': fund_extra}


if __name__ == '__main__':
    with open('data/fund_codes.json', 'w', encoding='utf-8') as fin:
        json.dump(list(set(compare_index + fund + fund_extra)), fin)

**Comment by luolovehk** [comment]
File "C:\jj\generate_output.py", line 85, in <module>
    worksheet.cell(3 + ind, 2, tmp_data[item][1])  # name
KeyError: '510300'

**Comment by sorahjy** [comment]
请问你是运行run.sh这个脚本来跑的吗？我这边改成你的代码能跑通，没有遇到你的问题

**Comment by luolovehk** [comment]
> 请问你是运行run.sh这个脚本来跑的吗？我这边改成你的代码能跑通，没有遇到你的问题

 我之前是直接run.sh跑的，也没报错。后来才发现是模块没安装。

**Comment by sorahjy** [comment]
bug fixed
